SCREEN_WIDTH = 700
SCREEN_HEIGHT = 700

NUM_BOIDS = 20
MAX_SPEED = 3
DRAW_COLLISION = False
DRAW_VISION = False
VISION_RANGE = 70
COLLISION_RANGE = 30

FORCE_PRIORITY_LIST = (
    'boundary', 'avoidance', 'velocity_matching', 'center_mass',
)

V_WEIGHT = 0.4
CM_WEIGHT = 0.3
AV_WEIGHT = 0.6
B_WEIGHT = 0.7
